/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorInicio;
import Modelo.RegistroCandidatos.Alcalde;
import Modelo.Resultados.ConsultasResultados;
import Modelo.Resultados.Departamento;
import Modelo.Resultados.Municipio;
import Vista.CambiarListas.combo.CustomUI;
import java.awt.Color;
import java.awt.event.FocusEvent;
import java.awt.event.ItemEvent;
import javax.swing.BorderFactory;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JTextField;
import javax.swing.border.Border;
import javax.swing.plaf.ComboBoxUI;

/**
 *
 * @author Allan Crack
 */
public class Alcaldes extends javax.swing.JDialog {

    /**
     * Creates new form Alcaldes
     */
    public Alcaldes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        estilosCombobox(Muncipios);
        estilosCombobox(listaDepartamentos);
        insertarDepartamentos();
        gif();
        
    }
    
    public void gif(){
        if(imagenCandidatura.getIcon() == null){//si no hay ninguna imagen
            votos.setText("Nombre Alcalde");
            
            votos.setForeground(new Color(105,116,112));
            
            
            campoNombre.setText("Votos");
            campoNombre.setForeground(new Color(105,116,112));
            
            
            jLabel1.setVisible(false);
        }else{
            jLabel1.setVisible(true);
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JPanel();
        cerrar = new javax.swing.JLabel();
        tituloLabel = new javax.swing.JLabel();
        panelAbajo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelImagen = new javax.swing.JPanel();
        imagenCandidatura = new javax.swing.JLabel();
        campoNombre = new javax.swing.JTextField();
        Muncipios = new javax.swing.JComboBox<>();
        listaDepartamentos = new javax.swing.JComboBox<>();
        votos = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setBackground(new java.awt.Color(0, 123, 200));
        Titulo.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 0, 3, new java.awt.Color(223, 224, 224)));
        Titulo.setLayout(null);

        cerrar.setFont(new java.awt.Font("Raleway", 1, 36)); // NOI18N
        cerrar.setForeground(new java.awt.Color(239, 243, 245));
        cerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cerrar.setText("x");
        cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cerrarMouseExited(evt);
            }
        });
        Titulo.add(cerrar);
        cerrar.setBounds(380, 10, 60, 43);

        tituloLabel.setBackground(new java.awt.Color(239, 243, 245));
        tituloLabel.setFont(new java.awt.Font("Raleway Black", 1, 34)); // NOI18N
        tituloLabel.setForeground(new java.awt.Color(239, 243, 245));
        tituloLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloLabel.setText("Alcaldes");
        Titulo.add(tituloLabel);
        tituloLabel.setBounds(0, 10, 440, 60);

        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 70));

        panelAbajo.setBackground(new java.awt.Color(40, 45, 49));
        panelAbajo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(223, 224, 224), 3));
        panelAbajo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/confetti.gif"))); // NOI18N
        panelAbajo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 27, 410, 328));

        panelImagen.setBackground(new java.awt.Color(33, 46, 54));
        panelImagen.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(223, 224, 224), 1, true));

        imagenCandidatura.setFont(new java.awt.Font("Open Sans", 1, 15)); // NOI18N
        imagenCandidatura.setForeground(new java.awt.Color(239, 243, 245));
        imagenCandidatura.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panelImagenLayout = new javax.swing.GroupLayout(panelImagen);
        panelImagen.setLayout(panelImagenLayout);
        panelImagenLayout.setHorizontalGroup(
            panelImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 248, Short.MAX_VALUE)
            .addGroup(panelImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(imagenCandidatura, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE))
        );
        panelImagenLayout.setVerticalGroup(
            panelImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 178, Short.MAX_VALUE)
            .addGroup(panelImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(imagenCandidatura, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE))
        );

        panelAbajo.add(panelImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 48, -1, -1));

        campoNombre.setBackground(new java.awt.Color(42, 59, 66));
        campoNombre.setFont(new java.awt.Font("Open Sans Light", 0, 15)); // NOI18N
        campoNombre.setForeground(new java.awt.Color(105, 116, 112));
        campoNombre.setText("Votos");
        campoNombre.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(232, 231, 222), 1, true), javax.swing.BorderFactory.createEmptyBorder(6, 6, 6, 6)));
        campoNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoNombreFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoNombreFocusLost(evt);
            }
        });
        campoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNombreActionPerformed(evt);
            }
        });
        panelAbajo.add(campoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 310, 129, -1));

        Muncipios.setBackground(new java.awt.Color(42, 59, 71));
        Muncipios.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        Muncipios.setForeground(new java.awt.Color(239, 243, 245));
        Muncipios.setMaximumRowCount(5);
        Muncipios.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(105, 116, 112), 1, true), javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 0)));
        Muncipios.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                MuncipiosItemStateChanged(evt);
            }
        });
        Muncipios.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                MuncipiosFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                MuncipiosFocusLost(evt);
            }
        });
        Muncipios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MuncipiosActionPerformed(evt);
            }
        });
        panelAbajo.add(Muncipios, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 420, 240, -1));

        listaDepartamentos.setBackground(new java.awt.Color(42, 59, 71));
        listaDepartamentos.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        listaDepartamentos.setForeground(new java.awt.Color(239, 243, 245));
        listaDepartamentos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        listaDepartamentos.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(105, 116, 112), 1, true), javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 0)));
        listaDepartamentos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                listaDepartamentosItemStateChanged(evt);
            }
        });
        listaDepartamentos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                listaDepartamentosFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                listaDepartamentosFocusLost(evt);
            }
        });
        panelAbajo.add(listaDepartamentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 375, 217, -1));

        votos.setEditable(false);
        votos.setBackground(new java.awt.Color(42, 59, 66));
        votos.setFont(new java.awt.Font("Open Sans Light", 0, 15)); // NOI18N
        votos.setForeground(new java.awt.Color(105, 116, 112));
        votos.setText("Nombre Alcalde");
        votos.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(232, 231, 222), 1, true), javax.swing.BorderFactory.createEmptyBorder(6, 6, 6, 6)));
        votos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                votosFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                votosFocusLost(evt);
            }
        });
        votos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                votosActionPerformed(evt);
            }
        });
        panelAbajo.add(votos, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 257, 250, -1));

        getContentPane().add(panelAbajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 440, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseClicked
           dispose();
          
        TablaGanadores tabla = new TablaGanadores();
        
        tabla.setVisible(true);
       
 
 
    
    }//GEN-LAST:event_cerrarMouseClicked
  public void insertarDepartamentos(){
    Departamento departamento = new Departamento();
        DefaultComboBoxModel modeloDepartamento = new DefaultComboBoxModel(departamento.mostrarDepartamentos());
        listaDepartamentos.setModel(modeloDepartamento); 
}

    private void MuncipiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MuncipiosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MuncipiosActionPerformed

    private void cerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseEntered
      Color color = new Color(200,200,200);
        cerrar.setForeground(color);
    }//GEN-LAST:event_cerrarMouseEntered

    private void cerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseExited
        Color color = new Color(239,243,245);
        cerrar.setForeground(color);
    }//GEN-LAST:event_cerrarMouseExited

    private void listaDepartamentosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_listaDepartamentosFocusGained
      Color azul = new Color(0, 109, 196);

            Border borde = BorderFactory.createEmptyBorder(2, 2, 2, 0);
            Border bordeDentro = BorderFactory.createLineBorder(azul, 2, true);

            Border bordeFinal = BorderFactory.createCompoundBorder(bordeDentro, borde);

           listaDepartamentos.setBorder(bordeFinal);
    }//GEN-LAST:event_listaDepartamentosFocusGained

    private void listaDepartamentosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_listaDepartamentosFocusLost
         Color sombras = new Color(105, 116, 112);

            Border borde = BorderFactory.createEmptyBorder(2, 2, 2, 0);
            Border bordeDentro = BorderFactory.createLineBorder(sombras, 1, true);

            Border bordeFinal = BorderFactory.createCompoundBorder(bordeDentro, borde);

            listaDepartamentos.setBorder(bordeFinal);
    }//GEN-LAST:event_listaDepartamentosFocusLost

    private void MuncipiosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_MuncipiosFocusGained
          Color azul = new Color(0, 109, 196);

            Border borde = BorderFactory.createEmptyBorder(2, 2, 2, 0);
            Border bordeDentro = BorderFactory.createLineBorder(azul, 2, true);

            Border bordeFinal = BorderFactory.createCompoundBorder(bordeDentro, borde);

           Muncipios.setBorder(bordeFinal);
    }//GEN-LAST:event_MuncipiosFocusGained

    private void MuncipiosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_MuncipiosFocusLost
          Color sombras = new Color(105, 116, 112);

            Border borde = BorderFactory.createEmptyBorder(2, 2, 2, 0);
            Border bordeDentro = BorderFactory.createLineBorder(sombras, 1, true);

            Border bordeFinal = BorderFactory.createCompoundBorder(bordeDentro, borde);

            Muncipios.setBorder(bordeFinal);
    }//GEN-LAST:event_MuncipiosFocusLost

    private void listaDepartamentosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_listaDepartamentosItemStateChanged
       
            Departamento depa = (Departamento) listaDepartamentos.getSelectedItem();
            Municipio municipio = new Municipio();

            DefaultComboBoxModel modeloMuncipio = new DefaultComboBoxModel(municipio.mostrarMuncipios(depa));

           Muncipios.setModel(modeloMuncipio);
    }//GEN-LAST:event_listaDepartamentosItemStateChanged

    private void MuncipiosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_MuncipiosItemStateChanged
    Color blanco = new Color(232,231,222);
    
        if(evt.getStateChange() == ItemEvent.SELECTED){
       
         if(Muncipios.getSelectedIndex() == 0){
             
         }else{
               ConsultasResultados modelo = new ConsultasResultados();
    
          Municipio muni = (Municipio) Muncipios.getSelectedItem();
          int nVotos = modelo.Maxvotos(muni);
          
           Alcalde alcalde = modelo.alcalde(nVotos,muni);
           
        campoNombre.setText(String.valueOf(alcalde.getVotos()) +" votos");
        campoNombre.setForeground(blanco);
        
        votos.setText(alcalde.getNombre());
        votos.setHorizontalAlignment(0);
        votos.setForeground(blanco);
        
        if(alcalde.getImagen()!=null){
              imagenCandidatura.setIcon(new ImageIcon(alcalde.getImagen())); 
        }else{
      imagenCandidatura.setIcon(null); 

        }
        
     

         }
            gif();
    }
    }//GEN-LAST:event_MuncipiosItemStateChanged

    private void campoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNombreActionPerformed
       
    }//GEN-LAST:event_campoNombreActionPerformed

    private void campoNombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoNombreFocusGained
              anadirFocusGainedCampos(evt, campoNombre, "Votos");    }//GEN-LAST:event_campoNombreFocusGained

    private void campoNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoNombreFocusLost
           anadirFocuslostCampos(evt, campoNombre, "Votos");
    }//GEN-LAST:event_campoNombreFocusLost

    private void votosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_votosFocusGained
       anadirFocusGainedCampos(evt, votos, "Nombre Alcalde");
    }//GEN-LAST:event_votosFocusGained

    private void votosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_votosFocusLost
        anadirFocuslostCampos(evt, votos, "Nombre Alcalde");
    }//GEN-LAST:event_votosFocusLost

    private void votosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_votosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_votosActionPerformed

     public void anadirFocusGainedCampos(FocusEvent e, JTextField campo, String placeholder) {
        if (e.getSource() == campo) {

            if (campo.getText().trim().equals(placeholder)) {
                campo.setText("");
                campo.setForeground(new Color(200, 205, 208));
            }

            Color ColorBlanco = new Color(239, 243, 245);
            Border borde = BorderFactory.createEmptyBorder(3, 3, 3, 3);
            Border bordeDentro = BorderFactory.createLineBorder(ColorBlanco, 1, true);

            Border bordeFinal = BorderFactory.createCompoundBorder(bordeDentro, borde);

            campo.setBorder(bordeFinal);

        }
    }
        
        public void anadirFocuslostCampos(FocusEvent e, JTextField campo, String placeholder) {

        if (e.getSource() == campo) {
            if (campo.getText().trim().equals(placeholder) || campo.getText().equals("")) {
                campo.setText(placeholder);
                campo.setForeground(new Color(105, 116, 112));
            }

            Color ColorGris = new Color(118, 118, 118);
            Border borde = BorderFactory.createEmptyBorder(3, 3, 3, 3);
            Border bordeDentro = BorderFactory.createLineBorder(ColorGris, 1, true);

            Border bordeFinal = BorderFactory.createCompoundBorder(bordeDentro, borde);

            campo.setBorder(bordeFinal);

        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Alcaldes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Alcaldes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Alcaldes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Alcaldes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Alcaldes dialog = new Alcaldes(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    private void estilosCombobox(JComboBox j){
         CustomUI custom = new CustomUI();
       ComboBoxUI diseño= custom.createUI(j);
        j.setUI(diseño);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> Muncipios;
    private javax.swing.JPanel Titulo;
    public javax.swing.JTextField campoNombre;
    public javax.swing.JLabel cerrar;
    public javax.swing.JLabel imagenCandidatura;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JComboBox<String> listaDepartamentos;
    private javax.swing.JPanel panelAbajo;
    public javax.swing.JPanel panelImagen;
    private javax.swing.JLabel tituloLabel;
    public javax.swing.JTextField votos;
    // End of variables declaration//GEN-END:variables
}
