/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorCandidatosRegistro;
import Controlador.ControladorInicio;
import Controlador.ControladorRegistro;
import Controlador.ControladorResultados;
import Modelo.RegistroCandidatos.Alcalde;
import Modelo.RegistroCandidatos.ConsultasCandidatos;
import Modelo.RegistroCandidatos.ConsultasVotaciones;
import Modelo.RegistroCandidatos.Diputado;
import Modelo.RegistroCandidatos.PartidoPolitico;
import Modelo.RegistroCandidatos.Presidente;
import Modelo.Resultados.ConsultasResultados;
import Modelo.Votantes.Consultas;
import Modelo.Votantes.Votante;
import java.awt.Color;
import java.awt.event.FocusEvent;
import javafx.scene.Parent;
import javax.swing.BorderFactory;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.border.Border;


public class ContaseñaSalir extends javax.swing.JDialog {

    public ContaseñaSalir(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
     setUndecorated(true);
        initComponents();
        setLocationRelativeTo(null);
        
      
    }

       public void anadirFocusGainedCampos(JPasswordField campo,String placeholder){
       
           String infomracion = new String(campo.getPassword()); //obteniendo la contraseña
       
             if(infomracion.equals(placeholder)){
                campo.setText("");
                campo.setForeground(new Color(200, 205, 208));
                campo.setEchoChar('*');//EL SET ECHO CHAR ME PONE QUE DIGITO ESTARA AQUI EN EL CAM0O
            }
             
          Color ColorBlanco = new Color(239,243,245);
          Border borde = BorderFactory.createEmptyBorder(6,6,6,6);
          Border bordeDentro = BorderFactory.createLineBorder(ColorBlanco, 1, true);
         
         
          Border bordeFinal = BorderFactory.createCompoundBorder(bordeDentro, borde);
         
        campo.setBorder(bordeFinal);
            
       }
       
       public void anadirFocuslostCampos(JPasswordField campo,String placeholder){
        
           String inform = new String(campo.getPassword());
           
                    if(inform.trim().equals(placeholder) || inform.equals("")){
                campo.setText(placeholder);
                campo.setForeground(new Color(105,116,112));
                campo.setEchoChar( (char)0 );
            }
             
          Color ColorGris = new Color(118,118,118);
          Border borde = BorderFactory.createEmptyBorder(6,6,6,6);
          Border bordeDentro = BorderFactory.createLineBorder(ColorGris, 1, true);
         
          Border bordeFinal = BorderFactory.createCompoundBorder(bordeDentro, borde);
         
        campo.setBorder(bordeFinal);
              
               }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Titulo = new javax.swing.JPanel();
        tituloLabel = new javax.swing.JLabel();
        cerrar = new javax.swing.JLabel();
        Partenferior = new javax.swing.JPanel();
        MostrarContraseña = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        PartidosPoliticos = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        PartidosPoliticos1 = new javax.swing.JLabel();
        insertarCandidato = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(33, 46, 54));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setBackground(new java.awt.Color(0, 123, 200));
        Titulo.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 0, 3, new java.awt.Color(223, 224, 224)));
        Titulo.setLayout(null);

        tituloLabel.setBackground(new java.awt.Color(239, 243, 245));
        tituloLabel.setFont(new java.awt.Font("Raleway Black", 1, 27)); // NOI18N
        tituloLabel.setForeground(new java.awt.Color(239, 243, 245));
        tituloLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloLabel.setText("Verificación de administrador");
        Titulo.add(tituloLabel);
        tituloLabel.setBounds(20, 10, 460, 60);

        cerrar.setBackground(new java.awt.Color(255, 96, 91));
        cerrar.setFont(new java.awt.Font("Raleway ExtraBold", 0, 24)); // NOI18N
        cerrar.setForeground(new java.awt.Color(239, 243, 245));
        cerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cerrar.setText("x");
        cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cerrar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cerrarFocusGained(evt);
            }
        });
        cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cerrarMouseExited(evt);
            }
        });
        Titulo.add(cerrar);
        cerrar.setBounds(480, 0, 20, 40);

        jPanel1.add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 70));

        Partenferior.setBackground(new java.awt.Color(40, 45, 49));
        Partenferior.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(223, 224, 224), 3));
        Partenferior.setLayout(null);

        MostrarContraseña.setBackground(new java.awt.Color(40, 45, 49));
        MostrarContraseña.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        MostrarContraseña.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                MostrarContraseñaFocusGained(evt);
            }
        });
        MostrarContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarContraseñaActionPerformed(evt);
            }
        });
        Partenferior.add(MostrarContraseña);
        MostrarContraseña.setBounds(460, 380, 21, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Controlador/imagenes/kisspng-computer-icons-login-scalable-vector-graphics-emai-5be737694adcc1.6333251315418796573066.png"))); // NOI18N
        Partenferior.add(jLabel1);
        jLabel1.setBounds(120, 80, 250, 260);

        PartidosPoliticos.setFont(new java.awt.Font("Raleway", 1, 22)); // NOI18N
        PartidosPoliticos.setForeground(new java.awt.Color(240, 240, 240));
        PartidosPoliticos.setText("Administrador");
        Partenferior.add(PartidosPoliticos);
        PartidosPoliticos.setBounds(170, 340, 151, 30);

        password.setBackground(new java.awt.Color(42, 59, 71));
        password.setFont(new java.awt.Font("Open Sans Light", 0, 15)); // NOI18N
        password.setForeground(new java.awt.Color(105, 116, 112));
        password.setText("Ingrese la contraseña de acceso");
        password.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(118, 118, 118), 1, true), javax.swing.BorderFactory.createEmptyBorder(6, 6, 6, 6)));
        password.setEchoChar((char)0);
        password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordFocusLost(evt);
            }
        });
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        Partenferior.add(password);
        password.setBounds(50, 380, 400, 40);

        PartidosPoliticos1.setFont(new java.awt.Font("Raleway", 1, 16)); // NOI18N
        PartidosPoliticos1.setForeground(new java.awt.Color(240, 240, 240));
        PartidosPoliticos1.setText("Partidos Politicos:");
        Partenferior.add(PartidosPoliticos1);
        PartidosPoliticos1.setBounds(15, 33, 137, 19);

        insertarCandidato.setBackground(new java.awt.Color(17, 146, 238));
        insertarCandidato.setFont(new java.awt.Font("Open Sans Semibold", 0, 15)); // NOI18N
        insertarCandidato.setForeground(new java.awt.Color(255, 255, 255));
        insertarCandidato.setText("Ingresar");
        insertarCandidato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertarCandidatoActionPerformed(evt);
            }
        });
        Partenferior.add(insertarCandidato);
        insertarCandidato.setBounds(170, 440, 150, 40);

        jPanel1.add(Partenferior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 530));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insertarCandidatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertarCandidatoActionPerformed
        String contraseña = "tengoHAMBRE";
        String imputIngresado = new String(password.getPassword());
        
        if(!contraseña.equals(imputIngresado)){//si la contraseña no es igual a esto
             Border bordePrecaucixd = BorderFactory.createLineBorder(new Color(255, 96, 91), 2, true);
              
             Border borde = BorderFactory.createEmptyBorder(6,6,6,6);
             Border bordePrecaucion  = BorderFactory.createCompoundBorder(borde, bordePrecaucixd);
             password.setBorder(bordePrecaucion);
                             JOptionPane.showMessageDialog(password, "Contraseña incorrecta","ERROR",0,imagenNice("\\Imagenes\\error.png", 40, 40)); 

        }else{
               dispose();
           TablaGanadores tabla = new TablaGanadores();
           tabla.setLocationRelativeTo(null);
           tabla.setVisible(true);
        
           
        }
        
    
   
    }//GEN-LAST:event_insertarCandidatoActionPerformed

    
          public Icon imagenNice(String path,int ancho,int alto){
       Icon imagen = new ImageIcon(new ImageIcon(getClass().getResource(path)).getImage().
                     getScaledInstance(ancho,alto,java.awt.Image.SCALE_SMOOTH));
  
   
   return imagen;
          }
    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusLost
        anadirFocuslostCampos(password, "Ingrese la contraseña de acceso");
    }//GEN-LAST:event_passwordFocusLost

    private void passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusGained
        anadirFocusGainedCampos(password, "Ingrese la contraseña de acceso");
    }//GEN-LAST:event_passwordFocusGained

    private void cerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseClicked
        dispose();
        InterfazInicio interfaz = new InterfazInicio();
    Controlador.ControladorInicio controlar = new ControladorInicio(interfaz);
    
    controlar.inicarApp();
    }//GEN-LAST:event_cerrarMouseClicked

    private void cerrarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cerrarFocusGained
       
       
        
    }//GEN-LAST:event_cerrarFocusGained

    private void cerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseEntered
       Color color = new Color(255,96,91);
       cerrar.setForeground(color);
       
    }//GEN-LAST:event_cerrarMouseEntered

    private void cerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseExited
        Color color = new Color(239,243,245);
       cerrar.setForeground(color);
    }//GEN-LAST:event_cerrarMouseExited

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged

    }//GEN-LAST:event_formMouseDragged

    private void MostrarContraseñaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_MostrarContraseñaFocusGained

    }//GEN-LAST:event_MostrarContraseñaFocusGained

    private void MostrarContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarContraseñaActionPerformed
        if(MostrarContraseña.isSelected()){
            String imputIngresado = new String(password.getPassword());

            password.setEchoChar( (char)0 );
        }else{
            password.setEchoChar('*');//EL SET ECHO CHAR ME PONE QUE DIGITO ESTARA AQUI EN EL CAM0O
        }

    }//GEN-LAST:event_MostrarContraseñaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContaseñaSalir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContaseñaSalir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContaseñaSalir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContaseñaSalir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ContaseñaSalir dialog = new ContaseñaSalir(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox MostrarContraseña;
    private javax.swing.JPanel Partenferior;
    private javax.swing.JLabel PartidosPoliticos;
    private javax.swing.JLabel PartidosPoliticos1;
    private javax.swing.JPanel Titulo;
    public javax.swing.JLabel cerrar;
    public javax.swing.JButton insertarCandidato;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel tituloLabel;
    // End of variables declaration//GEN-END:variables
}
