/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorCandidatosRegistro;
import Controlador.ControladorRegistro;
import FiveCodMover.FiveCodMoverJFrame;
import Modelo.RegistroCandidatos.Alcalde;
import Modelo.RegistroCandidatos.ConsultasCandidatos;
import Modelo.RegistroCandidatos.PartidoPolitico;
import Modelo.RegistroCandidatos.Presidente;
import Modelo.Votantes.Consultas;
import Modelo.Votantes.Votante;

/**
 *
 * @author Allan Crack
 */
public class InterfazInicio extends javax.swing.JFrame {

    /**
     * Creates new form InterfazInicio
     */
    public InterfazInicio() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Titulo = new javax.swing.JPanel();
        cerrar = new javax.swing.JLabel();
        tituloLabel = new javax.swing.JLabel();
        Partenferior = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        RegistrarUsuarios = new javax.swing.JButton();
        entrar = new javax.swing.JButton();
        RegistrarCandiatos1 = new javax.swing.JButton();
        resultados = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Open Sans", 0, 10)); // NOI18N
        setUndecorated(true);
        setResizable(false);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setBackground(new java.awt.Color(0, 123, 200));
        Titulo.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 0, 3, new java.awt.Color(223, 224, 224)));
        Titulo.setLayout(null);

        cerrar.setBackground(new java.awt.Color(255, 96, 91));
        cerrar.setFont(new java.awt.Font("Raleway ExtraBold", 0, 36)); // NOI18N
        cerrar.setForeground(new java.awt.Color(239, 243, 245));
        cerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cerrar.setText("x");
        cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarMouseClicked(evt);
            }
        });
        Titulo.add(cerrar);
        cerrar.setBounds(450, 10, 30, 40);

        tituloLabel.setBackground(new java.awt.Color(239, 243, 245));
        tituloLabel.setFont(new java.awt.Font("Raleway Black", 1, 34)); // NOI18N
        tituloLabel.setForeground(new java.awt.Color(239, 243, 245));
        tituloLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloLabel.setText("Elecciones 2020");
        Titulo.add(tituloLabel);
        tituloLabel.setBounds(0, 10, 490, 60);

        jPanel1.add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 70));

        Partenferior.setBackground(new java.awt.Color(40, 45, 49));
        Partenferior.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(223, 224, 224), 3));
        Partenferior.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(240, 139, 39));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Controlador/imagenes/kisspng-us-presidential-election-2016-voting-primary-elect-elections-5b4801910bce38.8726825715314456490484 (1).png"))); // NOI18N
        Partenferior.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 450, 350));

        jLabel1.setFont(new java.awt.Font("Open Sans", 1, 27)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(239, 243, 245));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BIENVENIDO");
        Partenferior.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 250, -1));

        RegistrarUsuarios.setBackground(new java.awt.Color(17, 146, 238));
        RegistrarUsuarios.setFont(new java.awt.Font("Open Sans Semibold", 0, 14)); // NOI18N
        RegistrarUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        RegistrarUsuarios.setText("Registrar Votantes");
        RegistrarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarUsuariosActionPerformed(evt);
            }
        });
        Partenferior.add(RegistrarUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, 270, 40));

        entrar.setBackground(new java.awt.Color(240, 139, 39));
        entrar.setFont(new java.awt.Font("Open Sans Semibold", 0, 14)); // NOI18N
        entrar.setForeground(new java.awt.Color(255, 255, 255));
        entrar.setText("Entrar a la Sala");
        entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrarActionPerformed(evt);
            }
        });
        Partenferior.add(entrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 480, 270, 40));

        RegistrarCandiatos1.setBackground(new java.awt.Color(17, 146, 238));
        RegistrarCandiatos1.setFont(new java.awt.Font("Open Sans Semibold", 0, 14)); // NOI18N
        RegistrarCandiatos1.setForeground(new java.awt.Color(255, 255, 255));
        RegistrarCandiatos1.setText("Registrar Candidatos");
        RegistrarCandiatos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarCandiatos1ActionPerformed(evt);
            }
        });
        Partenferior.add(RegistrarCandiatos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 420, 270, 40));

        resultados.setBackground(new java.awt.Color(152, 202, 63));
        resultados.setFont(new java.awt.Font("Open Sans Semibold", 0, 14)); // NOI18N
        resultados.setForeground(new java.awt.Color(255, 255, 255));
        resultados.setText("Ver Resultados");
        resultados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultadosActionPerformed(evt);
            }
        });
        Partenferior.add(resultados, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 540, 270, 40));

        jPanel1.add(Partenferior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 490, 630));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void entrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrarActionPerformed
       NumeroIdentidad numero = new NumeroIdentidad(this, true);
       dispose();
       numero.setVisible(true);
    }//GEN-LAST:event_entrarActionPerformed

    private void cerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseClicked
     

    }//GEN-LAST:event_cerrarMouseClicked

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
       FiveCodMoverJFrame.MouseDraggedFrame(evt, this);
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
         FiveCodMoverJFrame.MousePressed(evt);
    }//GEN-LAST:event_formMousePressed

    private void RegistrarCandiatos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarCandiatos1ActionPerformed
        Contaseña constra = new Contaseña(this, true);
        dispose();
        
        
        
        constra.setVisible(true);
        
        
    }//GEN-LAST:event_RegistrarCandiatos1ActionPerformed

    private void RegistrarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarUsuariosActionPerformed
     
        Votante votante = new Votante();
    Consultas consultas = new Consultas();
    Registro appRegistro = new Registro();
    //aca le paso los 3 elementos de mi plicacion para inciar todo
   ControladorRegistro controlador = new ControladorRegistro(appRegistro, consultas, votante);
   controlador.iniciarVentana();
   dispose();
   
   
    }//GEN-LAST:event_RegistrarUsuariosActionPerformed

    private void resultadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultadosActionPerformed
        ContaseñaResultados constra = new ContaseñaResultados(this, true);
        dispose();
        constra.setVisible(true);
        
    }//GEN-LAST:event_resultadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Partenferior;
    public javax.swing.JButton RegistrarCandiatos1;
    public javax.swing.JButton RegistrarUsuarios;
    private javax.swing.JPanel Titulo;
    public javax.swing.JLabel cerrar;
    public javax.swing.JButton entrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JButton resultados;
    private javax.swing.JLabel tituloLabel;
    // End of variables declaration//GEN-END:variables
}
