/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import FiveCodMover.FiveCodMoverJFrame;
import Vista.CambiarListas.combo.CambiarJtable;
import Vista.CambiarListas.combo.CustomUI;
import java.awt.Color;
import java.awt.Font;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.plaf.ComboBoxUI;

/**
 *
 * @author Allan Crack
 */
public class InterfazResultados extends javax.swing.JFrame {

   
    public InterfazResultados() {
        initComponents();
        estilosCombobox(municipios);
        estilosCombobox(departamentos);
        estilosCombobox(candidatos);
        estilosTablas();
        
    }
    
    public Font fuente(){
       Font fuente  = nombre1.getFont();
       
       return fuente;
    }

    public void estilosTablas(){
        tabla.getTableHeader().setBackground(new Color(0,123,200));
        tabla.getTableHeader().setFont(fuente());
        tabla.getTableHeader().setForeground(new Color(250,250,250));
        tabla.getTableHeader().setBorder(panelImagen1.getBorder());
        tabla.setBorder(panelImagen1.getBorder());
        tabla.setSelectionBackground(new Color(0,123,200));
        tabla.setSelectionForeground(Color.lightGray);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelInferior = new javax.swing.JPanel();
        panelPeque = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        candidatos = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        panelRegiones = new javax.swing.JPanel();
        departamentos = new javax.swing.JComboBox<>();
        municipios = new javax.swing.JComboBox<>();
        panelNormal = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        panelbig = new javax.swing.JPanel();
        panelImagen1 = new javax.swing.JPanel();
        imagenPresidente = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        nombre1 = new javax.swing.JLabel();
        campoNombre = new javax.swing.JTextField();
        partidoPolitico = new javax.swing.JLabel();
        imagenPartidoPolitico = new javax.swing.JPanel();
        imagenPartido = new javax.swing.JLabel();
        campoPorcentaje = new javax.swing.JTextField();
        campoPartido = new javax.swing.JTextField();
        campoVotos = new javax.swing.JTextField();
        nombre2 = new javax.swing.JLabel();
        nombre3 = new javax.swing.JLabel();
        btnDetener = new javax.swing.JButton();
        insertar = new javax.swing.JLabel();
        PanelTitulo = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        cerrar = new javax.swing.JLabel();
        MENOS = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelInferior.setBackground(new java.awt.Color(40, 45, 49));
        PanelInferior.setToolTipText("");
        PanelInferior.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelPeque.setBackground(new java.awt.Color(33, 46, 54));
        panelPeque.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(223, 224, 224), 1, true), "Lista de Candidatos", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Raleway Light", 0, 15), new java.awt.Color(239, 243, 245))); // NOI18N
        panelPeque.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelPeque.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        candidatos.setBackground(new java.awt.Color(42, 59, 71));
        candidatos.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        candidatos.setForeground(new java.awt.Color(239, 243, 245));
        candidatos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        candidatos.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(105, 116, 112), 1, true), javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 0)));
        panelPeque.add(candidatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 30, 170, -1));

        jScrollPane1.setBackground(new java.awt.Color(37, 50, 60));
        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setViewportBorder(new javax.swing.border.LineBorder(new java.awt.Color(10, 10, 10), 1, true));
        jScrollPane1.setFont(new java.awt.Font("Raleway", 1, 14)); // NOI18N

        tabla.setAutoCreateRowSorter(true);
        tabla.setBackground(new java.awt.Color(37, 50, 60));
        tabla.setFont(new java.awt.Font("Open Sans", 0, 15)); // NOI18N
        tabla.setForeground(new java.awt.Color(239, 243, 245));
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre", "Partido Político", "Votos"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla.setGridColor(new java.awt.Color(239, 243, 245));
        tabla.setRowHeight(25);
        tabla.setRowMargin(5);
        tabla.setRowSelectionAllowed(false);
        jScrollPane1.setViewportView(tabla);

        panelPeque.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 450, 240));

        panelRegiones.setBackground(new java.awt.Color(37, 50, 60));
        panelRegiones.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(239, 243, 245), 1, true));
        panelRegiones.setPreferredSize(new java.awt.Dimension(250, 180));

        departamentos.setBackground(new java.awt.Color(42, 59, 71));
        departamentos.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        departamentos.setForeground(new java.awt.Color(239, 243, 245));
        departamentos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        departamentos.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(105, 116, 112), 1, true), javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 0)));

        municipios.setBackground(new java.awt.Color(42, 59, 71));
        municipios.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        municipios.setForeground(new java.awt.Color(239, 243, 245));
        municipios.setMaximumRowCount(5);
        municipios.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(105, 116, 112), 1, true), javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 0)));

        javax.swing.GroupLayout panelRegionesLayout = new javax.swing.GroupLayout(panelRegiones);
        panelRegiones.setLayout(panelRegionesLayout);
        panelRegionesLayout.setHorizontalGroup(
            panelRegionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRegionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(municipios, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(departamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelRegionesLayout.setVerticalGroup(
            panelRegionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegionesLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(departamentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(municipios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 32, Short.MAX_VALUE))
        );

        panelPeque.add(panelRegiones, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, 220, 120));

        panelNormal.setBackground(new java.awt.Color(37, 50, 60));
        panelNormal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(239, 243, 245), 1, true));
        panelNormal.setPreferredSize(new java.awt.Dimension(250, 180));

        javax.swing.GroupLayout panelNormalLayout = new javax.swing.GroupLayout(panelNormal);
        panelNormal.setLayout(panelNormalLayout);
        panelNormalLayout.setHorizontalGroup(
            panelNormalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 188, Short.MAX_VALUE)
        );
        panelNormalLayout.setVerticalGroup(
            panelNormalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );

        panelPeque.add(panelNormal, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, 190, 50));

        PanelInferior.add(panelPeque, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 700, 300));

        jPanel1.setBackground(new java.awt.Color(40, 45, 49));
        jPanel1.setForeground(new java.awt.Color(40, 45, 49));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        PanelInferior.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 630, -1, 70));

        panelbig.setBackground(new java.awt.Color(33, 46, 54));
        panelbig.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(223, 224, 224), 1, true), "Informacion Candidato", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Raleway Light", 0, 15), new java.awt.Color(239, 243, 245))); // NOI18N
        panelbig.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelImagen1.setBackground(new java.awt.Color(37, 50, 60));
        panelImagen1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(239, 243, 245), 1, true));
        panelImagen1.setPreferredSize(new java.awt.Dimension(250, 180));

        javax.swing.GroupLayout panelImagen1Layout = new javax.swing.GroupLayout(panelImagen1);
        panelImagen1.setLayout(panelImagen1Layout);
        panelImagen1Layout.setHorizontalGroup(
            panelImagen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imagenPresidente, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
        );
        panelImagen1Layout.setVerticalGroup(
            panelImagen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imagenPresidente, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
        );

        panelbig.add(panelImagen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 250, 180));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator2.setMinimumSize(new java.awt.Dimension(50, 1));
        jSeparator2.setPreferredSize(new java.awt.Dimension(50, 1));
        panelbig.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 21, 1, 250));

        nombre1.setFont(new java.awt.Font("Open Sans Semibold", 0, 16)); // NOI18N
        nombre1.setForeground(new java.awt.Color(239, 243, 245));
        nombre1.setText("Porcentaje:");
        panelbig.add(nombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, -1, 30));

        campoNombre.setEditable(false);
        campoNombre.setBackground(new java.awt.Color(42, 59, 66));
        campoNombre.setFont(new java.awt.Font("Open Sans Light", 0, 15)); // NOI18N
        campoNombre.setForeground(new java.awt.Color(105, 116, 112));
        campoNombre.setText("Nombre Candidato");
        campoNombre.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(118, 118, 118), 1, true), javax.swing.BorderFactory.createEmptyBorder(6, 6, 6, 6)));
        panelbig.add(campoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 220, 30));

        partidoPolitico.setFont(new java.awt.Font("Open Sans Semibold", 0, 14)); // NOI18N
        partidoPolitico.setForeground(new java.awt.Color(239, 243, 245));
        partidoPolitico.setText("Partido Político:");
        panelbig.add(partidoPolitico, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 160, 90));

        imagenPartidoPolitico.setBackground(new java.awt.Color(37, 50, 60));
        imagenPartidoPolitico.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(223, 224, 224), 1, true));

        javax.swing.GroupLayout imagenPartidoPoliticoLayout = new javax.swing.GroupLayout(imagenPartidoPolitico);
        imagenPartidoPolitico.setLayout(imagenPartidoPoliticoLayout);
        imagenPartidoPoliticoLayout.setHorizontalGroup(
            imagenPartidoPoliticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 97, Short.MAX_VALUE)
            .addGroup(imagenPartidoPoliticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(imagenPartidoPoliticoLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(imagenPartido, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        imagenPartidoPoliticoLayout.setVerticalGroup(
            imagenPartidoPoliticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 69, Short.MAX_VALUE)
            .addGroup(imagenPartidoPoliticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(imagenPartidoPoliticoLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(imagenPartido, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        panelbig.add(imagenPartidoPolitico, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, -1, -1));

        campoPorcentaje.setEditable(false);
        campoPorcentaje.setBackground(new java.awt.Color(42, 59, 66));
        campoPorcentaje.setFont(new java.awt.Font("Open Sans Light", 0, 15)); // NOI18N
        campoPorcentaje.setForeground(new java.awt.Color(105, 116, 112));
        campoPorcentaje.setText("Porcentaje Votos");
        campoPorcentaje.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(118, 118, 118), 1, true), javax.swing.BorderFactory.createEmptyBorder(6, 6, 6, 6)));
        panelbig.add(campoPorcentaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 220, 140, 30));

        campoPartido.setEditable(false);
        campoPartido.setBackground(new java.awt.Color(42, 59, 66));
        campoPartido.setFont(new java.awt.Font("Open Sans Light", 0, 15)); // NOI18N
        campoPartido.setForeground(new java.awt.Color(105, 116, 112));
        campoPartido.setText("Partido Político");
        campoPartido.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(118, 118, 118), 1, true), javax.swing.BorderFactory.createEmptyBorder(6, 6, 6, 6)));
        panelbig.add(campoPartido, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 240, 30));

        campoVotos.setEditable(false);
        campoVotos.setBackground(new java.awt.Color(42, 59, 66));
        campoVotos.setFont(new java.awt.Font("Open Sans Light", 0, 15)); // NOI18N
        campoVotos.setForeground(new java.awt.Color(105, 116, 112));
        campoVotos.setText("Votos");
        campoVotos.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(118, 118, 118), 1, true), javax.swing.BorderFactory.createEmptyBorder(6, 6, 6, 6)));
        panelbig.add(campoVotos, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, 180, 30));

        nombre2.setFont(new java.awt.Font("Open Sans Semibold", 0, 16)); // NOI18N
        nombre2.setForeground(new java.awt.Color(239, 243, 245));
        nombre2.setText("Nombre: ");
        panelbig.add(nombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 30));

        nombre3.setFont(new java.awt.Font("Open Sans Semibold", 0, 16)); // NOI18N
        nombre3.setForeground(new java.awt.Color(239, 243, 245));
        nombre3.setText("Votos: ");
        panelbig.add(nombre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, -1, 30));

        PanelInferior.add(panelbig, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 620, 290));

        btnDetener.setBackground(new java.awt.Color(255, 96, 91));
        btnDetener.setFont(new java.awt.Font("Open Sans Semibold", 0, 16)); // NOI18N
        btnDetener.setForeground(new java.awt.Color(255, 255, 255));
        btnDetener.setText("Detener elecciones");
        btnDetener.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetenerActionPerformed(evt);
            }
        });
        PanelInferior.add(btnDetener, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 640, 190, 40));
        PanelInferior.add(insertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 590, -1, -1));

        getContentPane().add(PanelInferior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 740, 710));

        PanelTitulo.setBackground(new java.awt.Color(240, 147, 43));
        PanelTitulo.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 0, 2, new java.awt.Color(223, 224, 224)));
        PanelTitulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setFont(new java.awt.Font("Raleway Black", 0, 36)); // NOI18N
        titulo.setForeground(new java.awt.Color(239, 243, 245));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Resultados elecciones 2020");
        PanelTitulo.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 70));

        cerrar.setFont(new java.awt.Font("Raleway", 1, 36)); // NOI18N
        cerrar.setForeground(new java.awt.Color(239, 243, 245));
        cerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cerrar.setText("x");
        cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarMouseClicked(evt);
            }
        });
        PanelTitulo.add(cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 3, 39, 50));

        MENOS.setFont(new java.awt.Font("Raleway", 1, 36)); // NOI18N
        MENOS.setForeground(new java.awt.Color(239, 243, 245));
        MENOS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MENOS.setText("-");
        MENOS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MENOS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MENOSMouseClicked(evt);
            }
        });
        PanelTitulo.add(MENOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(675, 3, 30, 50));

        getContentPane().add(PanelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseClicked

    }//GEN-LAST:event_cerrarMouseClicked

    private void MENOSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MENOSMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_MENOSMouseClicked

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
       FiveCodMoverJFrame.MousePressed(evt);

    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
       FiveCodMoverJFrame.MouseDraggedFrame(evt, this);
    }//GEN-LAST:event_formMouseDragged

    private void btnDetenerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetenerActionPerformed
          int salir =1;//
      salir  = JOptionPane.showConfirmDialog(null,"¿Está seguro que desea detener las elecciones? ", "¿El futuro de Honduras esta en juego!!",JOptionPane.YES_NO_OPTION,-1 ,imagenNice("\\imagenes\\interrogacion.png", 40, 40));
      
       
      if(salir == 0){
           dispose();
        ContaseñaSalir contra = new ContaseñaSalir(this, true);
        contra.setVisible(true);
        
       
        
      }
        
        salir = 1;
        
        
    }//GEN-LAST:event_btnDetenerActionPerformed

      public Icon imagenNice(String path,int ancho,int alto){
       Icon imagen = new ImageIcon(new ImageIcon(getClass().getResource(path)).getImage().
                     getScaledInstance(ancho,alto,java.awt.Image.SCALE_SMOOTH));
  
   
   return imagen;
   }
    
     private void estilosCombobox(JComboBox j){
         CustomUI custom = new CustomUI();
       ComboBoxUI diseño= custom.createUI(j);
        j.setUI(diseño);
    }
     
  /*
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      
            
            
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new InterfazResultados().setVisible(true);
                }
            });
      
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel MENOS;
    private javax.swing.JPanel PanelInferior;
    private javax.swing.JPanel PanelTitulo;
    public javax.swing.JButton btnDetener;
    public javax.swing.JTextField campoNombre;
    public javax.swing.JTextField campoPartido;
    public javax.swing.JTextField campoPorcentaje;
    public javax.swing.JTextField campoVotos;
    public javax.swing.JComboBox<String> candidatos;
    public javax.swing.JLabel cerrar;
    public javax.swing.JComboBox<String> departamentos;
    public javax.swing.JLabel imagenPartido;
    public javax.swing.JPanel imagenPartidoPolitico;
    public javax.swing.JLabel imagenPresidente;
    public javax.swing.JLabel insertar;
    private javax.swing.JLabel jLabel3;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JSeparator jSeparator2;
    public javax.swing.JComboBox<String> municipios;
    private javax.swing.JLabel nombre1;
    private javax.swing.JLabel nombre2;
    private javax.swing.JLabel nombre3;
    private javax.swing.JPanel panelImagen1;
    public javax.swing.JPanel panelNormal;
    public javax.swing.JPanel panelPeque;
    public javax.swing.JPanel panelRegiones;
    private javax.swing.JPanel panelbig;
    public javax.swing.JLabel partidoPolitico;
    public javax.swing.JTable tabla;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
