/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorInicio;
import Controlador.ControladorSala;
import Modelo.RegistroCandidatos.Alcalde;
import Modelo.RegistroCandidatos.ConsultasCandidatos;
import Modelo.RegistroCandidatos.ConsultasVotaciones;
import Modelo.RegistroCandidatos.Diputado;
import Modelo.RegistroCandidatos.PartidoPolitico;
import Modelo.RegistroCandidatos.Presidente;
import Modelo.Votantes.Consultas;
import Modelo.Votantes.Votante;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author Allan Crack
 */
public class NumeroIdentidad extends javax.swing.JDialog {

    /**
     * Creates new form NumeroIdentidad
     */
    public NumeroIdentidad(java.awt.Frame parent, boolean modal) {
       
        super(parent, modal);
         this.setUndecorated(true);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Titulo = new javax.swing.JPanel();
        tituloLabel = new javax.swing.JLabel();
        cerrar = new javax.swing.JLabel();
        Partenferior = new javax.swing.JPanel();
        PartidosPoliticos = new javax.swing.JLabel();
        PartidosPoliticos1 = new javax.swing.JLabel();
        Ingresar = new javax.swing.JButton();
        campoIdentidad = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(33, 46, 54));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setBackground(new java.awt.Color(152, 202, 63));
        Titulo.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 0, 3, new java.awt.Color(223, 224, 224)));
        Titulo.setLayout(null);

        tituloLabel.setBackground(new java.awt.Color(239, 243, 245));
        tituloLabel.setFont(new java.awt.Font("Raleway Black", 1, 27)); // NOI18N
        tituloLabel.setForeground(new java.awt.Color(239, 243, 245));
        tituloLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloLabel.setText("Comprobacion de Votantes");
        Titulo.add(tituloLabel);
        tituloLabel.setBounds(20, 10, 460, 60);

        cerrar.setBackground(new java.awt.Color(255, 96, 91));
        cerrar.setFont(new java.awt.Font("Raleway ExtraBold", 0, 24)); // NOI18N
        cerrar.setForeground(new java.awt.Color(239, 243, 245));
        cerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cerrar.setText("x");
        cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cerrar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cerrarFocusGained(evt);
            }
        });
        cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cerrarMouseExited(evt);
            }
        });
        Titulo.add(cerrar);
        cerrar.setBounds(480, 0, 20, 40);

        jPanel1.add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 70));

        Partenferior.setBackground(new java.awt.Color(18, 31, 61));
        Partenferior.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(223, 224, 224), 3));
        Partenferior.setLayout(null);

        PartidosPoliticos.setFont(new java.awt.Font("Raleway", 1, 22)); // NOI18N
        PartidosPoliticos.setForeground(new java.awt.Color(240, 240, 240));
        PartidosPoliticos.setText("Ingrese su numero de identidad");
        Partenferior.add(PartidosPoliticos);
        PartidosPoliticos.setBounds(80, 250, 340, 30);

        PartidosPoliticos1.setFont(new java.awt.Font("Raleway", 1, 16)); // NOI18N
        PartidosPoliticos1.setForeground(new java.awt.Color(240, 240, 240));
        PartidosPoliticos1.setText("Partidos Politicos:");
        Partenferior.add(PartidosPoliticos1);
        PartidosPoliticos1.setBounds(15, 33, 137, 19);

        Ingresar.setBackground(new java.awt.Color(152, 190, 63));
        Ingresar.setFont(new java.awt.Font("Open Sans Semibold", 0, 15)); // NOI18N
        Ingresar.setForeground(new java.awt.Color(255, 255, 255));
        Ingresar.setText("Ingresar");
        Ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarActionPerformed(evt);
            }
        });
        Ingresar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                IngresarKeyTyped(evt);
            }
        });
        Partenferior.add(Ingresar);
        Ingresar.setBounds(190, 350, 150, 40);

        campoIdentidad.setBackground(new java.awt.Color(3, 9, 30));
        campoIdentidad.setFont(new java.awt.Font("Open Sans Light", 0, 16)); // NOI18N
        campoIdentidad.setForeground(new java.awt.Color(117, 142, 178));
        campoIdentidad.setText("Numero de Identidad");
        campoIdentidad.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(99, 123, 157), 1, true), javax.swing.BorderFactory.createEmptyBorder(6, 6, 6, 6)));
        campoIdentidad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoIdentidadFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoIdentidadFocusLost(evt);
            }
        });
        campoIdentidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoIdentidadActionPerformed(evt);
            }
        });
        campoIdentidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoIdentidadKeyTyped(evt);
            }
        });
        Partenferior.add(campoIdentidad);
        campoIdentidad.setBounds(80, 290, 350, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Controlador/imagenes/kisspng-united-states-of-america-voting-election-ballot-bo-lampaposactualit-de-votre-dput-sur-votre-5c7fea08a23a97.2866433815518868566645 (1).png"))); // NOI18N
        Partenferior.add(jLabel1);
        jLabel1.setBounds(170, 100, 150, 130);

        jPanel1.add(Partenferior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 450));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cerrarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cerrarFocusGained

    }//GEN-LAST:event_cerrarFocusGained

    private void cerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseClicked
        dispose();  
        InterfazInicio interfaz = new InterfazInicio();
    Controlador.ControladorInicio controlar = new ControladorInicio(interfaz);  
    
    controlar.inicarApp();
    
    }//GEN-LAST:event_cerrarMouseClicked

    private void cerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseEntered
        Color color = new Color(255,96,91);
        cerrar.setForeground(color);

    }//GEN-LAST:event_cerrarMouseEntered

    private void cerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseExited
        Color color = new Color(239,243,245);
        cerrar.setForeground(color);
    }//GEN-LAST:event_cerrarMouseExited

    private void IngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarActionPerformed
 if(campoIdentidad.getText().length() <= 12 && campoIdentidad.getText().length() >=1){
   bordesErrorCampoIdentidad();     
      JOptionPane.showMessageDialog(campoIdentidad, "Numero de identidad Incorrecto","ERROR",0,imagenNice("\\Imagenes\\error.png", 40, 40)); 

 }else{
     Consultas consulta = new Consultas();
     Votante votante = consulta.buscarUsuario(campoIdentidad.getText());
  
     
     if(votante == null){
         bordesErrorCampoIdentidad();     
      JOptionPane.showMessageDialog(campoIdentidad, "Ese numero de Identidad no esta registrado","ERROR",0,imagenNice("\\Imagenes\\error.png", 40, 40)); 

     }else if(consulta.verificarUsuarioVoto(votante) > 0){
          
       if(votante.getGenero().equals("Femenino")){
         JOptionPane.showMessageDialog(campoIdentidad, "La votante "+votante.getNombre()+" ya registro sus votos","ERROR",0,imagenNice("\\Imagenes\\error.png", 40, 40)); 

       }  else if(votante.getGenero().equals("Masculino")){
      JOptionPane.showMessageDialog(campoIdentidad, "El votante "+votante.getNombre()+" ya registro sus votos","ERROR",0,imagenNice("\\Imagenes\\error.png", 40, 40)); 

       }
         
 
         
     }else if(consulta.getAcceso(votante) == 1){
   
         JOptionPane.showMessageDialog(campoIdentidad, "Este usuario no tiene acceso a la sala","ERROR",0,imagenNice("\\Imagenes\\error.png", 40, 40)); 

     }else{
  votante.setIdMunicipio(consulta.obtenerIdMuncipio(votante));
  
  votante.setGenero(votante.getGenero());
        
  
  votante.setIdDepartamento(consulta.obtenerIdDepartamento(votante));
  
  JOptionPane.showMessageDialog(null, "BIENVENIDO A LA SALA DE VOTACIONES "+"\n\nUsuario: "+votante.getNombre()+"\nDepartamento: "+votante.getDepartamento()+"\nMunicipio: "+votante.getMunicpio(),"Usuario encontrado",JOptionPane.PLAIN_MESSAGE,imagenNice("\\Imagenes\\soldado.png", 40, 40));
  
 
  
  dispose();
        //instanciando la sala de votaciones
       SalaVotaciones sala = new SalaVotaciones();
    PartidoPolitico partido = new PartidoPolitico();
    Alcalde alcalde = new Alcalde();
    Presidente presidente = new Presidente();
    Diputado diputado = new Diputado();
    ConsultasVotaciones modelo = new ConsultasVotaciones();
          ConsultasCandidatos modeloCandidatos = new ConsultasCandidatos();

       Controlador.ControladorSala controlador = new ControladorSala(votante, sala, partido, alcalde, presidente, diputado, modelo,modeloCandidatos);
        controlador.iniciar();
     }
     
 }
 
 

    }//GEN-LAST:event_IngresarActionPerformed

    private void campoIdentidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoIdentidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoIdentidadActionPerformed

    private void campoIdentidadFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoIdentidadFocusGained
        if(campoIdentidad.getText().trim().equals("Numero de Identidad")){
         campoIdentidad.setText("");
         campoIdentidad.setForeground(Color.WHITE);
     } 
        Border bordeCampo =  BorderFactory.createLineBorder( new Color(51, 177, 255),2,true );
       Border campoVacio = BorderFactory.createEmptyBorder(6, 6, 6, 6);
       Border agregarBorde = BorderFactory.createCompoundBorder(bordeCampo, campoVacio);
       
          campoIdentidad.setBorder(agregarBorde);    
    }//GEN-LAST:event_campoIdentidadFocusGained

    private void campoIdentidadFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoIdentidadFocusLost
   
        if(campoIdentidad.getText().trim().equals("Numero de Identidad") ||
                 campoIdentidad.getText().equals("")){
         campoIdentidad.setText("Numero de Identidad");
         campoIdentidad.setForeground(new Color(117,142,178));
         
         
             
         }
        
         Border bordeCampo =  BorderFactory.createLineBorder( new Color(99,123,157),1,true );
       Border campoVacio = BorderFactory.createEmptyBorder(6, 6, 6, 6);
       Border agregarBorde = BorderFactory.createCompoundBorder(bordeCampo, campoVacio);
       
        campoIdentidad.setBorder(agregarBorde);   
           
    }//GEN-LAST:event_campoIdentidadFocusLost

    private void IngresarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IngresarKeyTyped
      
    }//GEN-LAST:event_IngresarKeyTyped

    private void campoIdentidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoIdentidadKeyTyped
        
        if(!Character.isDigit(evt.getKeyChar()) || campoIdentidad.getText().length() >= 13){//verifivando si el caracter es un digito parra que no me escriba mamonadas deletras en el numero de identidad y ademas no podra escribir mas de 16 digitos 
          evt.consume();//si el digito ingresado no es un 
        }//si el usuario ingresa una letra no le dejare escribir nada gracias al consume y el Caracter es digit me ayuda a validar si un caracter es un digito y este evento al ser un keyTyped se ejecutara cada vez que yo presione una tecla
       
    }//GEN-LAST:event_campoIdentidadKeyTyped
   private void bordesErrorCampoIdentidad(){
           Border bordePrecaucion = BorderFactory.createLineBorder(new Color(255, 96, 91), 2, true);
           Border campoVacio = BorderFactory.createEmptyBorder(6, 6, 6, 6);
           Border agregarBorde = BorderFactory.createCompoundBorder(bordePrecaucion, campoVacio);
           campoIdentidad.setBorder(agregarBorde);
    }
   
      public Icon imagenNice(String path,int ancho,int alto){
       Icon imagen = new ImageIcon(new ImageIcon(getClass().getResource(path)).getImage().
                     getScaledInstance(ancho,alto,java.awt.Image.SCALE_SMOOTH));
  
   
   return imagen;
   }
     
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NumeroIdentidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NumeroIdentidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NumeroIdentidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NumeroIdentidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NumeroIdentidad dialog = new NumeroIdentidad(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Ingresar;
    private javax.swing.JPanel Partenferior;
    private javax.swing.JLabel PartidosPoliticos;
    private javax.swing.JLabel PartidosPoliticos1;
    private javax.swing.JPanel Titulo;
    public javax.swing.JTextField campoIdentidad;
    public javax.swing.JLabel cerrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel tituloLabel;
    // End of variables declaration//GEN-END:variables
}
