/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import FiveCodMover.FiveCodMoverJFrame;
import java.awt.Color;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import Modelo.RegistroCandidatos.Presidente;
import Vista.Diputados.principal;

/**
 *
 * @author Allan Crack
 */
public class TablaGanadores extends javax.swing.JFrame {

    /**
     * Creates new form TablaGanadores
     */
    public TablaGanadores() {
        initComponents();
        setLocationRelativeTo(null);
       
        
    }

   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Titulo = new javax.swing.JPanel();
        cerrar = new javax.swing.JLabel();
        tituloLabel = new javax.swing.JLabel();
        cerrar1 = new javax.swing.JLabel();
        Partenferior = new javax.swing.JPanel();
        Presidente = new javax.swing.JButton();
        alcalde = new javax.swing.JButton();
        Diputados = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setBackground(new java.awt.Color(240, 147, 43));
        Titulo.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 0, 3, new java.awt.Color(223, 224, 224)));
        Titulo.setLayout(null);

        cerrar.setBackground(new java.awt.Color(255, 96, 91));
        cerrar.setFont(new java.awt.Font("Raleway ExtraBold", 0, 36)); // NOI18N
        cerrar.setForeground(new java.awt.Color(239, 243, 245));
        cerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cerrar.setText("-");
        cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cerrarMouseExited(evt);
            }
        });
        Titulo.add(cerrar);
        cerrar.setBounds(350, 10, 30, 40);

        tituloLabel.setBackground(new java.awt.Color(239, 243, 245));
        tituloLabel.setFont(new java.awt.Font("Raleway Black", 1, 34)); // NOI18N
        tituloLabel.setForeground(new java.awt.Color(239, 243, 245));
        tituloLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloLabel.setText("Ganadores");
        Titulo.add(tituloLabel);
        tituloLabel.setBounds(0, 10, 410, 60);

        cerrar1.setBackground(new java.awt.Color(255, 96, 91));
        cerrar1.setFont(new java.awt.Font("Raleway ExtraBold", 0, 36)); // NOI18N
        cerrar1.setForeground(new java.awt.Color(239, 243, 245));
        cerrar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cerrar1.setText("x");
        cerrar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cerrar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrar1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cerrar1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cerrar1MouseExited(evt);
            }
        });
        Titulo.add(cerrar1);
        cerrar1.setBounds(380, 10, 30, 40);

        jPanel1.add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 70));

        Partenferior.setBackground(new java.awt.Color(40, 45, 49));
        Partenferior.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(223, 224, 224), 3));
        Partenferior.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Presidente.setBackground(new java.awt.Color(17, 146, 238));
        Presidente.setFont(new java.awt.Font("Open Sans Semibold", 0, 14)); // NOI18N
        Presidente.setForeground(new java.awt.Color(255, 255, 255));
        Presidente.setText("Presidente Ganador");
        Presidente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PresidenteActionPerformed(evt);
            }
        });
        Partenferior.add(Presidente, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 220, 40));

        alcalde.setBackground(new java.awt.Color(17, 146, 238));
        alcalde.setFont(new java.awt.Font("Open Sans Semibold", 0, 14)); // NOI18N
        alcalde.setForeground(new java.awt.Color(255, 255, 255));
        alcalde.setText("Alcaldes que ganaron");
        alcalde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alcaldeActionPerformed(evt);
            }
        });
        Partenferior.add(alcalde, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 450, 220, 40));

        Diputados.setBackground(new java.awt.Color(17, 146, 238));
        Diputados.setFont(new java.awt.Font("Open Sans Semibold", 0, 14)); // NOI18N
        Diputados.setForeground(new java.awt.Color(255, 255, 255));
        Diputados.setText("Diputados que ganaron");
        Diputados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiputadosActionPerformed(evt);
            }
        });
        Partenferior.add(Diputados, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, 220, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/copa.png"))); // NOI18N
        Partenferior.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 270, 280));

        jPanel1.add(Partenferior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 420, 560));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseClicked
  this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_cerrarMouseClicked

    private void PresidenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PresidenteActionPerformed
      dispose();
      PresidenteS presidente = new PresidenteS(this,true);
      presidente.setVisible(true);

    }//GEN-LAST:event_PresidenteActionPerformed

    private void alcaldeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alcaldeActionPerformed
            dispose();  
        Alcaldes alcaldeInterfaz = new Alcaldes(this, true);
           alcaldeInterfaz.setVisible(true);
            
       
    }//GEN-LAST:event_alcaldeActionPerformed

    private void DiputadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiputadosActionPerformed
       dispose(); 
       principal prin = new principal();
       prin.setVisible(true);
    }//GEN-LAST:event_DiputadosActionPerformed

    private void cerrar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrar1MouseClicked
          int salir =1;//
      salir  = JOptionPane.showConfirmDialog(null,"¿Está seguro que desea salir de la aplicacion? ", "Salir",JOptionPane.YES_NO_OPTION,-1 ,imagenNice("\\imagenes\\interrogacion.png", 40, 40));
      
       
      if(salir == 0){
        System.exit(0);
      }
        
        salir = 1;
        
       
    }//GEN-LAST:event_cerrar1MouseClicked
  public Icon imagenNice(String path,int ancho,int alto){
       Icon imagen = new ImageIcon(new ImageIcon(getClass().getResource(path)).getImage().
                     getScaledInstance(ancho,alto,java.awt.Image.SCALE_SMOOTH));
  
   
   return imagen;
   }
    private void cerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseEntered
       Color color = new Color(200,200,200);
        cerrar.setForeground(color);
    }//GEN-LAST:event_cerrarMouseEntered

    private void cerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseExited
           Color color = new Color(239,243,245);
        cerrar.setForeground(color);
    }//GEN-LAST:event_cerrarMouseExited

    private void cerrar1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrar1MouseEntered
        Color color = new Color(200,200,200);
        cerrar1.setForeground(color);
        
    }//GEN-LAST:event_cerrar1MouseEntered

    private void cerrar1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrar1MouseExited
           Color color = new Color(239,243,245);
        cerrar1.setForeground(color);
    }//GEN-LAST:event_cerrar1MouseExited

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
              FiveCodMoverJFrame.MouseDraggedFrame(evt, this);

    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
            FiveCodMoverJFrame.MousePressed(evt);

    }//GEN-LAST:event_formMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TablaGanadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TablaGanadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TablaGanadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TablaGanadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TablaGanadores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Diputados;
    private javax.swing.JPanel Partenferior;
    public javax.swing.JButton Presidente;
    private javax.swing.JPanel Titulo;
    public javax.swing.JButton alcalde;
    public javax.swing.JLabel cerrar;
    public javax.swing.JLabel cerrar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel tituloLabel;
    // End of variables declaration//GEN-END:variables
}
