/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.PanelesDiputados;

import Vista.InterfazInicio;

/**
 *
 * @author Allan Crack
 */
public class Colón extends javax.swing.JPanel {

    /**
     * Creates new form Atlantida
     */
    public Colón() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JPanel();
        tituloLabel = new javax.swing.JLabel();
        cerrar = new javax.swing.JLabel();

        setBackground(new java.awt.Color(40, 45, 49));
        setPreferredSize(new java.awt.Dimension(724, 517));

        Titulo.setBackground(new java.awt.Color(0, 123, 200));
        Titulo.setLayout(null);

        tituloLabel.setBackground(new java.awt.Color(239, 243, 245));
        tituloLabel.setFont(new java.awt.Font("Raleway Black", 1, 39)); // NOI18N
        tituloLabel.setForeground(new java.awt.Color(239, 243, 245));
        tituloLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloLabel.setText("Departamento de Colón");
        Titulo.add(tituloLabel);
        tituloLabel.setBounds(0, 10, 720, 60);

        cerrar.setBackground(new java.awt.Color(255, 96, 91));
        cerrar.setFont(new java.awt.Font("Raleway ExtraBold", 0, 36)); // NOI18N
        cerrar.setForeground(new java.awt.Color(239, 243, 245));
        cerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cerrar.setText("x");
        cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cerrar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cerrarFocusGained(evt);
            }
        });
        cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cerrarMouseExited(evt);
            }
        });
        Titulo.add(cerrar);
        cerrar.setBounds(680, 10, 20, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 724, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 440, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cerrarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cerrarFocusGained

    }//GEN-LAST:event_cerrarFocusGained

    private void cerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseClicked
     
    }//GEN-LAST:event_cerrarMouseClicked

    private void cerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseEntered
        

    }//GEN-LAST:event_cerrarMouseEntered

    private void cerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseExited
       
    }//GEN-LAST:event_cerrarMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Titulo;
    public javax.swing.JLabel cerrar;
    private javax.swing.JLabel tituloLabel;
    // End of variables declaration//GEN-END:variables
}
