package Vista.Diputados;

import FiveCodMover.FiveCodMoverJFrame;
import Modelo.RegistroCandidatos.ConsultasCandidatos;
import Modelo.RegistroCandidatos.ConsultasVotaciones;
import Modelo.RegistroCandidatos.Diputado;
import Modelo.RegistroCandidatos.PartidoPolitico;
import Modelo.Resultados.ConsultasResultados;
import Modelo.Resultados.Departamento;
import Modelo.Resultados.Municipio;
import Vista.CambiarListas.combo.CustomUI;
import Vista.TablaGanadores;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusEvent;
import java.awt.event.ItemEvent;
import java.awt.image.BufferedImage;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.border.Border;
import javax.swing.plaf.ComboBoxUI;

/**
 *
 * @author JorgeLPR
 */
public class principal extends javax.swing.JFrame {
         //atributos de la clase   
        ConsultasVotaciones modelo = new ConsultasVotaciones();
        Diputado diputado;
        ConsultasCandidatos modeloCandiatos = new ConsultasCandidatos();//verificando las consultas en esta clase
        
    public principal() {
        initComponents();
        
        this.setLocationRelativeTo(null);
       
        estilosCombobox(listaDepartamentos);
        estilosCombobox(Ganadores2);
     insertarDepartamentos();
      gif();
        
    }
    
 public void insertarDepartamentos(){
    Departamento departamento = new Departamento();
        DefaultComboBoxModel modeloDepartamento = new DefaultComboBoxModel(departamento.mostrarDepartamentos3());
        listaDepartamentos.setModel(modeloDepartamento); 
}
    
 
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedor = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        panelPartido = new javax.swing.JPanel();
        panelImagenPartido = new javax.swing.JPanel();
        PartidoPolitico = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        panelbig1 = new javax.swing.JPanel();
        Ganadores2 = new javax.swing.JComboBox<>();
        listaDepartamentos = new javax.swing.JComboBox<>();
        Titulo = new javax.swing.JPanel();
        cerrar = new javax.swing.JLabel();
        tituloLabel = new javax.swing.JLabel();
        panelbig = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        panelImagen1 = new javax.swing.JPanel();
        ImagenGanadores = new javax.swing.JLabel();
        campoVotos = new javax.swing.JTextField();
        campoNombre = new javax.swing.JTextField();
        campoPartido = new javax.swing.JTextField();
        panelPartido1 = new javax.swing.JPanel();
        nCandidatos = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contenedor.setBackground(new java.awt.Color(40, 45, 49));
        contenedor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(223, 224, 224), 3));
        contenedor.setMinimumSize(new java.awt.Dimension(724, 670));
        contenedor.setPreferredSize(new java.awt.Dimension(724, 670));
        contenedor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(40, 45, 49));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        contenedor.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 630, -1, 60));

        panelPartido.setBackground(new java.awt.Color(33, 46, 54));
        panelPartido.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(223, 224, 224), 1, true), "Partido Político", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Raleway Light", 0, 15), new java.awt.Color(239, 243, 245))); // NOI18N
        panelPartido.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelImagenPartido.setBackground(new java.awt.Color(40, 45, 49));
        panelImagenPartido.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(223, 224, 224), 1, true));
        panelImagenPartido.setPreferredSize(new java.awt.Dimension(99, 72));

        javax.swing.GroupLayout panelImagenPartidoLayout = new javax.swing.GroupLayout(panelImagenPartido);
        panelImagenPartido.setLayout(panelImagenPartidoLayout);
        panelImagenPartidoLayout.setHorizontalGroup(
            panelImagenPartidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PartidoPolitico, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
        );
        panelImagenPartidoLayout.setVerticalGroup(
            panelImagenPartidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PartidoPolitico, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        panelPartido.add(panelImagenPartido, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 30, 99, 72));

        jLabel1.setFont(new java.awt.Font("Raleway Light", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(239, 243, 245));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nombre Partido");
        panelPartido.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 170, -1));

        contenedor.add(panelPartido, new org.netbeans.lib.awtextra.AbsoluteConstraints(553, 100, 190, 150));

        panelbig1.setBackground(new java.awt.Color(33, 46, 54));
        panelbig1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(223, 224, 224), 1, true), "Controlador Ganadores", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Raleway Light", 0, 15), new java.awt.Color(239, 243, 245))); // NOI18N

        Ganadores2.setBackground(new java.awt.Color(42, 59, 71));
        Ganadores2.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        Ganadores2.setForeground(new java.awt.Color(239, 243, 245));
        Ganadores2.setMaximumRowCount(6);
        Ganadores2.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(105, 116, 112), 1, true), javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 0)));
        Ganadores2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Ganadores2ItemStateChanged(evt);
            }
        });
        Ganadores2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Ganadores2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Ganadores2FocusLost(evt);
            }
        });

        listaDepartamentos.setBackground(new java.awt.Color(42, 59, 71));
        listaDepartamentos.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        listaDepartamentos.setForeground(new java.awt.Color(239, 243, 245));
        listaDepartamentos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        listaDepartamentos.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(105, 116, 112), 1, true), javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 0)));
        listaDepartamentos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                listaDepartamentosItemStateChanged(evt);
            }
        });
        listaDepartamentos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                listaDepartamentosFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                listaDepartamentosFocusLost(evt);
            }
        });

        javax.swing.GroupLayout panelbig1Layout = new javax.swing.GroupLayout(panelbig1);
        panelbig1.setLayout(panelbig1Layout);
        panelbig1Layout.setHorizontalGroup(
            panelbig1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelbig1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(listaDepartamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
            .addGroup(panelbig1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(Ganadores2, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelbig1Layout.setVerticalGroup(
            panelbig1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelbig1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(listaDepartamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Ganadores2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        contenedor.add(panelbig1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 490, 360, 130));

        Titulo.setBackground(new java.awt.Color(0, 123, 200));
        Titulo.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 3, new java.awt.Color(223, 224, 224)));
        Titulo.setLayout(null);

        cerrar.setFont(new java.awt.Font("Raleway", 1, 36)); // NOI18N
        cerrar.setForeground(new java.awt.Color(239, 243, 245));
        cerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cerrar.setText("x");
        cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cerrarMouseExited(evt);
            }
        });
        Titulo.add(cerrar);
        cerrar.setBounds(690, 10, 60, 43);

        tituloLabel.setBackground(new java.awt.Color(239, 243, 245));
        tituloLabel.setFont(new java.awt.Font("Raleway Black", 1, 34)); // NOI18N
        tituloLabel.setForeground(new java.awt.Color(239, 243, 245));
        tituloLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloLabel.setText("Diputados Ganadores ");
        Titulo.add(tituloLabel);
        tituloLabel.setBounds(0, 10, 750, 60);

        contenedor.add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 3, 760, 70));

        panelbig.setBackground(new java.awt.Color(33, 46, 54));
        panelbig.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(223, 224, 224), 1, true));
        panelbig.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/confetti.gif"))); // NOI18N
        panelbig.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 10, 460, -1));

        panelImagen1.setBackground(new java.awt.Color(37, 50, 60));
        panelImagen1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(239, 243, 245), 1, true));
        panelImagen1.setPreferredSize(new java.awt.Dimension(250, 180));

        javax.swing.GroupLayout panelImagen1Layout = new javax.swing.GroupLayout(panelImagen1);
        panelImagen1.setLayout(panelImagen1Layout);
        panelImagen1Layout.setHorizontalGroup(
            panelImagen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ImagenGanadores, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
        );
        panelImagen1Layout.setVerticalGroup(
            panelImagen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ImagenGanadores, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
        );

        panelbig.add(panelImagen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 250, 180));

        campoVotos.setEditable(false);
        campoVotos.setBackground(new java.awt.Color(42, 59, 66));
        campoVotos.setFont(new java.awt.Font("Open Sans Light", 0, 15)); // NOI18N
        campoVotos.setForeground(new java.awt.Color(105, 116, 112));
        campoVotos.setText("Votos Diputado");
        campoVotos.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(118, 118, 118), 1, true), javax.swing.BorderFactory.createEmptyBorder(6, 6, 6, 6)));
        campoVotos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoVotosFocusGained(evt);
            }
        });
        panelbig.add(campoVotos, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 170, 30));

        campoNombre.setEditable(false);
        campoNombre.setBackground(new java.awt.Color(42, 59, 66));
        campoNombre.setFont(new java.awt.Font("Open Sans Light", 0, 15)); // NOI18N
        campoNombre.setForeground(new java.awt.Color(105, 116, 112));
        campoNombre.setText("Nombre Diputado");
        campoNombre.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(118, 118, 118), 1, true), javax.swing.BorderFactory.createEmptyBorder(6, 6, 6, 6)));
        campoNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoNombreFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoNombreFocusLost(evt);
            }
        });
        panelbig.add(campoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 210, 30));

        campoPartido.setEditable(false);
        campoPartido.setBackground(new java.awt.Color(42, 59, 66));
        campoPartido.setFont(new java.awt.Font("Open Sans Light", 0, 15)); // NOI18N
        campoPartido.setForeground(new java.awt.Color(105, 116, 112));
        campoPartido.setText("Partido Político");
        campoPartido.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(118, 118, 118), 1, true), javax.swing.BorderFactory.createEmptyBorder(6, 6, 6, 6)));
        campoPartido.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoPartidoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoPartidoFocusLost(evt);
            }
        });
        panelbig.add(campoPartido, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 190, 30));

        contenedor.add(panelbig, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 103, 310, 360));

        panelPartido1.setBackground(new java.awt.Color(33, 46, 54));
        panelPartido1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(223, 224, 224), 1, true), "Numero de Ganadores", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Raleway Light", 0, 15), new java.awt.Color(239, 243, 245))); // NOI18N
        panelPartido1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nCandidatos.setEditable(false);
        nCandidatos.setBackground(new java.awt.Color(42, 59, 66));
        nCandidatos.setFont(new java.awt.Font("Open Sans Light", 0, 15)); // NOI18N
        nCandidatos.setForeground(new java.awt.Color(105, 116, 112));
        nCandidatos.setText("N Candidatos");
        nCandidatos.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(118, 118, 118), 1, true), javax.swing.BorderFactory.createEmptyBorder(6, 6, 6, 6)));
        nCandidatos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nCandidatosFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nCandidatosFocusLost(evt);
            }
        });
        panelPartido1.add(nCandidatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 150, 30));

        contenedor.add(panelPartido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 100, 190, 90));

        getContentPane().add(contenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 760, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listaDepartamentosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_listaDepartamentosItemStateChanged
        if(evt.getStateChange() == ItemEvent.SELECTED){
          
            if(listaDepartamentos.getSelectedIndex() !=0){
            Departamento depa = (Departamento) listaDepartamentos.getSelectedItem();
           int  limite =  modelo.LimiteDiputados(depa.getId_Departamento());
            ConsultasResultados cons = new ConsultasResultados();
        
            DefaultComboBoxModel ganadores = new DefaultComboBoxModel(cons.diputadosGanadores(depa, limite));
            Ganadores2.setModel(ganadores);
            tituloLabel.setText("Departamento de "+depa.getNombre());
         
        
            
            }else{
                   tituloLabel.setText("Diputados Ganadores");
                   jLabel1.setText("Nombre Partido");
                   Ganadores2.removeAllItems();
                   campoNombre.setText("Nombre Diputado");
                   campoPartido.setText("Partido Político");
                   campoVotos.setText("Votos Diputado");
                   nCandidatos.setText("N Candidatos");
                   ImagenGanadores.setIcon(null);
                   } 
              
          
        }
            gif(); 
        
    }//GEN-LAST:event_listaDepartamentosItemStateChanged

    private void listaDepartamentosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_listaDepartamentosFocusGained
        Color azul = new Color(0, 109, 196);

        Border borde = BorderFactory.createEmptyBorder(2, 2, 2, 0);
        Border bordeDentro = BorderFactory.createLineBorder(azul, 2, true);

        Border bordeFinal = BorderFactory.createCompoundBorder(bordeDentro, borde);

        listaDepartamentos.setBorder(bordeFinal);
    }//GEN-LAST:event_listaDepartamentosFocusGained

    private void listaDepartamentosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_listaDepartamentosFocusLost
        Color sombras = new Color(105, 116, 112);

        Border borde = BorderFactory.createEmptyBorder(2, 2, 2, 0);
        Border bordeDentro = BorderFactory.createLineBorder(sombras, 1, true);

        Border bordeFinal = BorderFactory.createCompoundBorder(bordeDentro, borde);

        listaDepartamentos.setBorder(bordeFinal);
    }//GEN-LAST:event_listaDepartamentosFocusLost

    private void cerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseClicked
        dispose();

        TablaGanadores tabla = new TablaGanadores();
        tabla.setLocationRelativeTo(null);
        tabla.setVisible(true);

    }//GEN-LAST:event_cerrarMouseClicked

    private void cerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseEntered
        Color color = new Color(200,200,200);
        cerrar.setForeground(color);
    }//GEN-LAST:event_cerrarMouseEntered

    private void cerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseExited
        Color color = new Color(239,243,245);
        cerrar.setForeground(color);
    }//GEN-LAST:event_cerrarMouseExited

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
FiveCodMoverJFrame.MouseDraggedFrame(evt, this);
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
            FiveCodMoverJFrame.MousePressed(evt);
    }//GEN-LAST:event_formMousePressed
   public void gif(){
        if(ImagenGanadores.getIcon() == null){
            jLabel2.setVisible(false);
        }else{
            jLabel2.setVisible(true);
        }
    }
    
    private void Ganadores2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Ganadores2ItemStateChanged
        if(evt.getStateChange() == ItemEvent.SELECTED){
           
            if(Ganadores2.getSelectedIndex() !=0){
            Color blanco = new Color(200, 205, 208);
            
            diputado = (Diputado) Ganadores2.getSelectedItem();
              int  limite =  modelo.LimiteDiputados(diputado.getId_Departamento());
            
              PartidoPolitico partido1 = new PartidoPolitico();
          
              partido1 = partido1.partido(diputado.getId_Partido());//obteniendo el partido dependiendo con el id de partido del diputado
            
            
            campoNombre.setText(diputado.getNombre());
            campoNombre.setForeground(blanco);
            campoNombre.setHorizontalAlignment(0);
            
            
            campoVotos.setText(String.valueOf(diputado.getVotos()) + " votos");
            campoVotos.setForeground(blanco);
            
            nCandidatos.setText(String.valueOf(limite) + " candidatos");
            nCandidatos.setForeground(blanco);
            
            campoPartido.setText(partido1.getNombre());
            campoPartido.setHorizontalAlignment(0);
            campoPartido.setForeground(blanco);
            
            ImagenGanadores.setIcon(new ImageIcon(diputado.getImagen()));
            
            BufferedImage imagx =  modeloCandiatos.imagenPartidos(partido1);//le mando todos los campos incializados
           
            PartidoPolitico.setIcon(new ImageIcon(imagx));
        
            jLabel1.setText(partido1.getNombre());
            }else{
                    tituloLabel.setText("Diputados Ganadores");
                   jLabel1.setText("Nombre Partido");
                   Ganadores2.removeAllItems();
                   campoNombre.setText("Nombre Diputado");
                   campoPartido.setText("Partido Político");
                   campoVotos.setText("Votos Diputado");
                   nCandidatos.setText("N Candidatos");
                   ImagenGanadores.setIcon(null); 
            }
            
        }
         gif();
            
    }//GEN-LAST:event_Ganadores2ItemStateChanged

    private void Ganadores2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Ganadores2FocusGained
               Color azul = new Color(0, 109, 196);

        Border borde = BorderFactory.createEmptyBorder(2, 2, 2, 0);
        Border bordeDentro = BorderFactory.createLineBorder(azul, 2, true);

        Border bordeFinal = BorderFactory.createCompoundBorder(bordeDentro, borde);

        Ganadores2.setBorder(bordeFinal);  
    }//GEN-LAST:event_Ganadores2FocusGained

    private void Ganadores2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Ganadores2FocusLost
         Color sombras = new Color(105, 116, 112);

        Border borde = BorderFactory.createEmptyBorder(2, 2, 2, 0);
        Border bordeDentro = BorderFactory.createLineBorder(sombras, 1, true);

        Border bordeFinal = BorderFactory.createCompoundBorder(bordeDentro, borde);

        Ganadores2.setBorder(bordeFinal); 
    }//GEN-LAST:event_Ganadores2FocusLost

    private void campoNombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoNombreFocusGained
        anadirFocusGainedCampos(evt, campoNombre, "Nombre Diputado");
    }//GEN-LAST:event_campoNombreFocusGained

    private void nCandidatosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nCandidatosFocusLost
      anadirFocuslostCampos(evt, nCandidatos, "N Candidatos");
    }//GEN-LAST:event_nCandidatosFocusLost

    private void campoPartidoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoPartidoFocusLost
        anadirFocuslostCampos(evt, campoPartido, "Partido Político");
    }//GEN-LAST:event_campoPartidoFocusLost

    private void campoNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoNombreFocusLost
         anadirFocuslostCampos(evt, campoNombre, "Nombre Diputado");
    }//GEN-LAST:event_campoNombreFocusLost

    private void campoPartidoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoPartidoFocusGained
            anadirFocusGainedCampos(evt, campoPartido, "Partido Político");    }//GEN-LAST:event_campoPartidoFocusGained

    private void nCandidatosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nCandidatosFocusGained
        anadirFocusGainedCampos(evt,nCandidatos, "Votos Diputado");
    }//GEN-LAST:event_nCandidatosFocusGained

    private void campoVotosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoVotosFocusGained
              anadirFocusGainedCampos(evt, campoVotos, "N Candidatos");    }//GEN-LAST:event_campoVotosFocusGained
 private void estilosCombobox(JComboBox j){
         CustomUI custom = new CustomUI();
       ComboBoxUI diseño= custom.createUI(j);
        j.setUI(diseño);
    }
 
 
    public void anadirFocusGainedCampos(FocusEvent e, JTextField campo, String placeholder) {
        if (e.getSource() == campo) {

            if (campo.getText().trim().equals(placeholder)) {
                campo.setText("");
                campo.setForeground(new Color(200, 205, 208));
            }

            Color ColorBlanco = new Color(239, 243, 245);
            Border borde = BorderFactory.createEmptyBorder(3, 3, 3, 3);
            Border bordeDentro = BorderFactory.createLineBorder(ColorBlanco, 1, true);

            Border bordeFinal = BorderFactory.createCompoundBorder(bordeDentro, borde);

            campo.setBorder(bordeFinal);

        }
    }
        
        public void anadirFocuslostCampos(FocusEvent e, JTextField campo, String placeholder) {

        if (e.getSource() == campo) {
            if (campo.getText().trim().equals(placeholder) || campo.getText().equals("")) {
                campo.setText(placeholder);
                campo.setForeground(new Color(105, 116, 112));
            }

            Color ColorGris = new Color(118, 118, 118);
            Border borde = BorderFactory.createEmptyBorder(3, 3, 3, 3);
            Border bordeDentro = BorderFactory.createLineBorder(ColorGris, 1, true);

            Border bordeFinal = BorderFactory.createCompoundBorder(bordeDentro, borde);

            campo.setBorder(bordeFinal);

        }
    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> Ganadores2;
    private javax.swing.JLabel ImagenGanadores;
    private javax.swing.JLabel PartidoPolitico;
    private javax.swing.JPanel Titulo;
    public javax.swing.JTextField campoNombre;
    public javax.swing.JTextField campoPartido;
    public javax.swing.JTextField campoVotos;
    public javax.swing.JLabel cerrar;
    private javax.swing.JPanel contenedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JComboBox<String> listaDepartamentos;
    public javax.swing.JTextField nCandidatos;
    private javax.swing.JPanel panelImagen1;
    public javax.swing.JPanel panelImagenPartido;
    private javax.swing.JPanel panelPartido;
    private javax.swing.JPanel panelPartido1;
    private javax.swing.JPanel panelbig;
    private javax.swing.JPanel panelbig1;
    private javax.swing.JLabel tituloLabel;
    // End of variables declaration//GEN-END:variables

    
}
